import { FileText, Download } from 'lucide-react';
import React, { useRef } from 'react';

const MedicalReport = ({ prediction, formData, patientId }) => {
  const contentToPrint = useRef(null);

  const handlePrint = () => {
    const printContents = contentToPrint.current.innerHTML;
    const originalContents = document.body.innerHTML;

    document.body.innerHTML = `
      <html>
        <head>
          <title>Medical Report</title>
          <style>
             body { font-family: sans-serif; color: black; background: white; padding: 20px; }
             h1 { color: #0f766e; border-bottom: 2px solid #0f766e; padding-bottom: 10px; }
             h2 { color: #334155; margin-top: 20px; }
             table { width: 100%; border-collapse: collapse; margin-top: 10px; }
             th, td { border: 1px solid #cbd5e1; padding: 12px; text-align: left; }
             th { background-color: #f1f5f9; }
             .highlight { font-weight: bold; color: #b91c1c; }
             .safe { color: #15803d; }
          </style>
        </head>
        <body>
          ${printContents}
        </body>
      </html>
    `;

    window.print();
    // Refresh page to restore React root
    window.location.reload(); 
  };

  return (
    <div className="glass-panel" style={{ marginTop: '2rem', padding: '2rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', borderBottom: '1px solid var(--border-dark)', paddingBottom: '1rem' }}>
        <h3 style={{ fontSize: '1.25rem', fontWeight: '700', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <FileText color="var(--color-healthcare-main)" /> Official Chronotherapy Consultation Report
        </h3>
        <button className="btn-primary" style={{ width: 'auto' }} onClick={handlePrint}>
          <Download size={18} /> Download PDF
        </button>
      </div>
      
      {/* Hidden print payload that will be captured by ref */}
      <div ref={contentToPrint} style={{ display: 'none' }}>
        <h1>ChronoMed AI Clinical Report</h1>
        <p><strong>Patient ID:</strong> {patientId}</p>
        <p><strong>Date Generated:</strong> {new Date().toLocaleDateString()}</p>
        <p><strong>Primary Condition:</strong> {formData.condition_name}</p>
        
        <h2>AI Prediction Summary</h2>
        <table>
          <tbody>
            <tr>
              <th>Forecasted Improvement Score</th>
              <td>{prediction.predicted_improvement_score.toFixed(2)} / 10</td>
            </tr>
            <tr>
              <th>Optimal Circadian Time (AI)</th>
              <td>{prediction.ai_recommended_time}:00</td>
            </tr>
            <tr>
              <th>Standard Guideline Time</th>
              <td>{prediction.doctor_recommended_time}:00</td>
            </tr>
            <tr>
              <th>Time Difference Warning</th>
              <td className={prediction.time_difference_hours >= 2 ? "highlight" : "safe"}>
                {prediction.time_difference_hours} hours offset 
                {prediction.time_difference_hours >= 2 ? ' (Clinical Override Needed)' : ''}
              </td>
            </tr>
          </tbody>
        </table>

        <h2>Patient Demographics & Vitals</h2>
        <table>
          <tbody>
            <tr>
              <th>Age</th><td>{formData.age} yrs</td>
              <th>Gender</th><td>{formData.gender === '1' ? 'Male' : 'Female'}</td>
            </tr>
            <tr>
              <th>Heart Rate</th><td>{formData.heart_rate} bpm</td>
              <th>Blood Glucose</th><td>{formData.glucose} mg/dL</td>
            </tr>
            <tr>
              <th>Cholesterol</th><td>{formData.cholesterol}</td>
              <th>Stress Level</th><td>{formData.stress} / 10</td>
            </tr>
            <tr>
              <th>Sleep Duration</th><td>{formData.sleep_duration} hrs</td>
              <th>Drug Class Code</th><td>{formData.drug}</td>
            </tr>
            <tr>
              <th>Dosage</th><td>{formData.dosage} mg</td>
              <th>Duration</th><td>{formData.duration} days</td>
            </tr>
          </tbody>
        </table>
        
        <p style={{ marginTop: '30px', fontSize: '12px', color: '#64748b' }}>
          *This report was auto-generated by the ChronoMed AI system. It requires physician review if chronotherapy time offsets exceed clinical thresholds.
        </p>
      </div>
      
      <div style={{ color: 'var(--text-muted)' }}>
        <p>Your clinical report has been generated. When you submit your request to the doctor, this report and its parameters will be sent for review.</p>
      </div>

    </div>
  );
};

export default MedicalReport;
